### ISSUE TITLE
Bug Report：Win10 使用 pnpm install 报错

### ISSUE THREAD

**Issue by Lercel** [nolebase/nolebase#24]
I install node modules failed.

![image](https://github.com/nolebase/nolebase/assets/92929085/7485da08-ad50-4b8b-8414-2d78c9464469)

And the solution maybe：https://github.com/lovell/sharp/issues/3833

```
sudo npm i -g cnpm
cnpm i sharp
```

**Comment by nekomeowww** [comment]
Can you provide me more details on your OS/System info?

Is it `Windows 10 64bit`?

1. `cnpm` may not work correctly since this project uses `pnpm` and the lock file that described the dependencies versions is only pnpm compatible.
2. This error is `node-gyp` related. Should check further discussions about `node-gyp` on `Windows`.
3. `sharp` is used to help to generate the preview images for each documentations (it looks like [this image](https://nolebase.ayaka.io/%E7%AC%94%E8%AE%B0/%F0%9F%93%9A%20%E4%B8%AA%E4%BA%BA%E7%9F%A5%E8%AF%86%E7%AE%A1%E7%90%86/og-%E4%B8%BA%E4%BB%80%E4%B9%88%20n%C3%B3l%C3%ABbase%20%E4%BB%8E%20creative%20commons%20%E5%8D%8F%E8%AE%AE%E7%9A%84%20by-nc-sa%20%E5%88%87%E6%8D%A2%E5%88%B0%E4%BA%86%20by-sa%EF%BC%9F.png) and will only be read by social media platforms and preview components such as Twitter, Lark, Telegram, Slack, etc., you can uninstall this dependency and remove the following code from `scripts/post-docs.ts` when developing, previewing and writing, or when you don't need it.

```typescript
;(async function () {
  buildOG() // remove this line
}()).catch((err) => {
  console.error(err)
  exit(1)
})
```

**Comment by nekomeowww** [comment]
Wait, in the error message you provided, it says `ETIMEOUT 20.205.243.166:443`, should relate to a network issue.

Do you live in China and behind the firewall? If so, are you able to setup proxy applications like CFW (Clash for Windows)? 
CFW should have the capabilities to enable proxies in both `CMD` and `Powershell`, you can turn it on in CFW's settings menu where "Tunnel" terms located.

Besides this, you can try to set a mirror that `cnpm` uses for `pnpm`:

To check the registry that set for `pnpm`:

```shell
pnpm get registry 
```

Temporarily for this installation:

```shell
pnpm --registry https://registry.npm.taobao.org install sharp
```

or

```shell
pnpm --registry https://registry.npmmirror.com/ install sharp
```

Across all terminals, projects, Powershell, and take effect permenantly:

```shell
pnpm config set registry https://registry.npm.taobao.org/
```

or

```shell
pnpm config set registry https://registry.npmmirror.com/
```

to recover to the default settings:

```shell
pnpm config set registry https://registry.npmjs.org
```

You can read more from here: https://juejin.cn/post/7054747440032776199

**Comment by Lercel** [comment]
Yeah, I would set up my proxy, and open the "Tunnel" in the menu. Many many thanks！~

**Comment by Lercel** [comment]
Yeah, I would set up my proxy, and open the "Tunnel" in the menu. Many many thanks！~
